### ISSUE TITLE
Yahoo url no longer working

### ISSUE THREAD

**Issue by alukito** [Waasi/yahoo_finanza#1]
Hello, 

It seems that yahoo has changed its env url. This url (`env=http://datatables.org/alltables.env`) no longer works. I tried to change it to `env=store://datatables.org/alltableswithkeys` and it works fine now.

Thanks.

**Comment by Waasi** [comment]
Hello and Thanks. I will work on this as soon as possible. Also if you would like to contribute let me know.

Regards.

**Comment by Waasi** [comment]
Hello @alukito 

As implemented in commit: [c5e783abeb567554b2ccfec6f0cde581f9fac9eb](https://github.com/Waasi/yahoo_finanza/commit/c5e783abeb567554b2ccfec6f0cde581f9fac9eb) the url has been changed. The package in hex.pm has been updated bumped to version 0.2.3. Therefore I am closing this issue.

Thanks again for reporting this. Regards.
